### ISSUE TITLE
Europe compilation is slow when there is not enough RAM

### ISSUE THREAD

**Issue by boxdot** [boxdot/osmflat-rs#31]
When compiling Europe (tried on machines with 8GB and 16GB RAM), the `node_id` to `node_index` mapping (osm node id is mapped to position/index in nodes flatdata vector) grows over the memory limit and is swapped. Nodes compilation finishes, however ways compilation is stuck due to random access in mapping data.

One possible solution would be to change the underlying mapping data structure such that it is accessed in a similar pattern to ways compilation.

**Comment by VeaaC** [comment]
This should be much better with the latest version: It needs significantly less RAM than before. Can you try again?

**Comment by boxdot** [comment]
Tried again on my old 8GB RAM machine. Peaked at 11 GB RAM usage and could not finish relations anymore (eta over 3h). I will try on my bigger machine and check the peak RAM consumption there.

**Comment by VeaaC** [comment]
There are two big blocks of data we keep in memory:
* The Id->Index mapping
* All strings/tags

We could actually offer a "low-RAM" mode that does 2 passes of the data, e.g. first extracting all strings/tags, and then a second pass resolving ids and writing nodes/ways/relations.

**Comment by VeaaC** [comment]
![image](https://user-images.githubusercontent.com/14972638/197706791-b62c1a9e-ccab-4ead-8107-a5776a0d40cf.png)

It's mostly the hashmap for strings and tags

**Comment by VeaaC** [comment]
If you are not against a sprinkle of unsafe code you can try out https://github.com/boxdot/osmflat-rs/pull/73 which reduces this from 14.9GB down to 9.5 GB

![image](https://user-images.githubusercontent.com/14972638/197774651-2039ee8a-f83b-443f-a2e6-8710cba30d8e.png)

**Comment by boxdot** [comment]
I managed to compile Europe on my old machine with 8 GB. Closing this.
